using System.Globalization;
using System.Windows;

namespace AqTracker;

/// <summary>Provides the application strings supported by the tracker UI.</summary>
public static class LocalizationManager
{
    public const string DefaultLanguageCode = "pt-BR";
    private const string EnglishLanguageCode = "en-US";
    private const string ResourcePrefix = "Loc.";

    private static readonly IReadOnlyDictionary<string, string> Portuguese = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["ClaudeProfile"] = "Perfil Claude",
        ["ClaudeNeedsReconnect"] = "Reconexão necessária",
        ["ShowClaudeProfile"] = "Exibir perfil Claude",
        ["ClaudeSignInHint"] = "Conecte sua conta Claude para acompanhar as cotas 5h e 7d.",
        ["ClaudeConnectedHint"] = "A cota do Claude é atualizada automaticamente.",
        ["SettingsGeneral"] = "Geral",
        ["SettingsAbout"] = "Sobre",
        ["ProfileColor"] = "Cor",
        ["AppTagline"] = "Cotas do Codex e do Claude",
        ["ClaudeAccentColor"] = "Cor do Claude",
        ["ClaudeConnected"] = "Conectado",
        ["ClaudeDisconnected"] = "Desconectado",
        ["ClaudeReconnect"] = "Reconectar Claude",
        ["ClaudeConnect"] = "Conectar Claude",
        ["ClaudeConnectCode"] = "Conectar com código",
        ["ClaudeManualFallback"] = "Conexão automática indisponível. Conclua no navegador e cole o código abaixo.",
        ["ClaudeDisconnect"] = "Desconectar",
        ["ClaudeConnectSettings"] = "Conectar Claude nas configurações",
        ["ClaudeStale"] = "Desatualizado",
        ["QuotaDataAsOf"] = "Dados de {0}",
        ["ClaudeWaitingBrowser"] = "Conclua o login no navegador (até 5 minutos).",
        ["ClaudePasteCode"] = "Cole o código de autorização (code#state).",
        ["ClaudeSubmitCode"] = "Conectar",
        ["ClaudeInvalidCode"] = "Código inválido, expirado ou de outro login. Inicie uma nova conexão.",
        ["ClaudeLoginFailed"] = "Não foi possível conectar. Tente novamente ou conecte com código.",
        ["ClaudeLoginCancelled"] = "Conexão cancelada ou expirada.",
        ["ClaudeBrowserDone"] = "Conexão autorizada. Esta janela pode ser fechada.",
        ["ClaudeInvalidCallback"] = "Resposta de autorização inválida. Retorne ao Tracker.",
        ["ProfileQuotaIndicator"] = "{0}: cota restante de {1}",
        ["AppTitle"] = "Agent Quota Tracker",
        ["Settings"] = "Configurações",
        ["CloseSettings"] = "Fechar configurações",
        ["CloseWindow"] = "Fechar janela",
        ["DetailedMode"] = "Modo detalhado",
        ["ShowInNotificationArea"] = "Exibir na área de notificação",
        ["FadeFloatingWidget"] = "Esmaecer widget flutuante",
        ["FloatingOpacity"] = "Opacidade",
        ["StartMinimizedWithWindows"] = "Iniciar minimizado com o Windows",
        ["ToggleDetailedMode"] = "Alternar modo compacto/detalhado",
        ["AlwaysOnTop"] = "Sempre no topo",
        ["Hide"] = "Ocultar",
        ["Show"] = "Mostrar",
        ["Refresh"] = "Atualizar",
        ["Exit"] = "Sair",
        ["DarkTheme"] = "Tema escuro",
        ["ToggleTheme"] = "Alternar tema claro ou escuro",
        ["AccentColor"] = "Cor de destaque",
        ["ChooseAccentColor"] = "Escolher cor de destaque",
        ["ChooseAccentColorTooltip"] = "Escolher a cor usada nos destaques",
        ["Language"] = "Idioma",
        ["Currency"] = "Moeda",
        ["UsdBrlRate"] = "Taxa USD para BRL (manual)",
        ["CodexPath"] = "Caminho do Codex",
        ["Browse"] = "Procurar",
        ["AutoDetect"] = "Auto",
        ["Test"] = "Testar",
        ["OpenLog"] = "Abrir log",
        ["Cancel"] = "Cancelar",
        ["Apply"] = "Aplicar",
        ["Agent"] = "Agent",
        ["Subagent"] = "Subagent",
        ["AgentsWorking"] = "{0} agentes trabalhando",
        ["AgentsWorkingTooltip"] = "Agentes trabalhando",
        ["ShowWorkingAgents"] = "Exibir agentes trabalhando",
        ["OpenAgentChat"] = "Abrir chat do agente",
        ["UnreadAgentCompletions"] = "Trabalhos concluídos não lidos",
        ["MarkAllCompletedAgentsRead"] = "Marcar todos os trabalhos concluídos como lidos",
        ["WeeklyQuotaIndicator"] = "Indicador de quota semanal restante",
        ["Working"] = "Em andamento",
        ["Waiting"] = "Aguardando",
        ["Completed"] = "Concluído",
        ["Failed"] = "Falhou",
        ["Cancelled"] = "Cancelado",
        ["Unknown"] = "Desconhecido",
        ["UnregisteredModel"] = "Modelo não registrado",
        ["Model"] = "Modelo",
        ["Effort"] = "Esforço",
        ["RunningFor"] = "Em execução há {0}",
        ["UsageRanking"] = "Ranking de uso",
        ["ConsumptionDetails"] = "Detalhes do consumo",
        ["Day"] = "dia",
        ["Week"] = "semana",
        ["Month"] = "mês",
        ["Weekly"] = "SEMANAL",
        ["FiveHourWindow"] = "JANELA 5H",
        ["TodayUpper"] = "HOJE",
        ["WeekUpper"] = "SEMANA",
        ["MonthUpper"] = "MÊS",
        ["RankingPeriodDay"] = "Período do ranking: dia",
        ["RankingPeriodWeek"] = "Período do ranking: semana",
        ["RankingPeriodMonth"] = "Período do ranking: mês",
        ["DailyUsageCurrentMonth"] = "USO DIÁRIO · MÊS ATUAL",
        ["DetailsByChat"] = "Detalhes por chat",
        ["SearchChats"] = "Buscar chats ou projetos",
        ["ClearSearch"] = "Limpar busca",
        ["Project"] = "Projeto",
        ["UnknownProject"] = "Sem projeto",
        ["NoChats"] = "Nenhum chat com uso neste mês.",
        ["PartialTariffEstimate"] = "Estimativa parcial: alguns modelos não têm tarifa",
        ["Quota"] = "Quota",
        ["WeeklyQuota"] = "Quota semanal",
        ["WeeklyQuotaRemaining"] = "Quota semanal restante",
        ["WeeklyQuotaInitial"] = "% 7d inicial",
        ["WeeklyQuotaRemainingShort"] = "% 7d restante",
        ["CompactQuota"] = "Indicador compacto de quota",
        ["QuotaNotReported"] = "Quota semanal não reportada",
        ["NoQuotaRecord"] = "sem registro de quota",
        ["LoadingWeeklyQuota"] = "Carregando quota semanal",
        ["Loading"] = "Carregando",
        ["InsufficientData"] = "Dados insuficientes para previsão",
        ["ShouldLastUntilReset"] = "Deve durar até o reset",
        ["LimitExhausted"] = "Limite esgotado",
        ["ExhaustionRisk"] = "Risco de esgotar antes do reset",
        ["ProjectedForecast"] = "{0} · {1} projetado",
        ["ExhaustsAround"] = "esgota por volta de {0}",
        ["Reset"] = "Redefinição",
        ["LiveData"] = "Dados ao vivo via Codex",
        ["NoLiveData"] = "Sem dados ao vivo",
        ["Costs"] = "Custos",
        ["NoTariff"] = "sem tarifa",
        ["EstimatedValues"] = "Valores estimados",
        ["CachedRead"] = "Leitura em cache",
        ["Input"] = "Entrada",
        ["Output"] = "Saída",
        ["Reasoning"] = "Raciocínio",
        ["Total"] = "Total",
        ["Connected"] = "Conectado",
        ["ConnectionError"] = "Erro de conexão",
        ["ConnectingToCodex"] = "Conectando ao Codex",
        ["StaleReconnecting"] = "Desatualizado: reconectando",
        ["StaleRetrying"] = "Desatualizado: tentando reconectar",
        ["TestFailed"] = "Teste falhou",
        ["CodexNotFound"] = "Erro: Codex CLI não encontrado",
        ["ConnectedWeeklyUnavailable"] = "Conectado - quota semanal indisponível",
        ["DayNumber"] = "Dia {0}",
        ["CodexConversation"] = "Conversa Codex",
        ["ConnectedWeeklyRemaining"] = "Conectado - quota semanal restante {0}",
        ["CheckForUpdates"] = "Verificar atualizações",
        ["UpdateCheckChecking"] = "Verificando atualizações…",
        ["UpdateCheckUpToDate"] = "Você já está na versão mais recente.",
        ["UpdateCheckFailed"] = "Não foi possível verificar atualizações.",
        ["UpdateCheckInProgress"] = "Verificação já em andamento…",
        ["UpdateAvailableTitle"] = "Atualização disponível",
        ["UpdateAvailableMessage"] = "Uma nova versão do Agent Quota Tracker está disponível: {0}",
        ["UpdateNow"] = "Atualizar",
        ["UpdateLater"] = "Adiar",
        ["UpdateDownloading"] = "Baixando atualização…",
        ["UpdateDownloadingPercent"] = "Baixando atualização… {0}%",
        ["UpdateInstalling"] = "Instalando e reiniciando…",
        ["UpdateFailed"] = "Falha ao atualizar. Tente novamente mais tarde."
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["ClaudeProfile"] = "Claude profile",
        ["ClaudeNeedsReconnect"] = "Reconnect required",
        ["ShowClaudeProfile"] = "Show Claude profile",
        ["ClaudeSignInHint"] = "Connect your Claude account to track its 5h and 7d quotas.",
        ["ClaudeConnectedHint"] = "Claude quota refreshes automatically.",
        ["SettingsGeneral"] = "General",
        ["SettingsAbout"] = "About",
        ["ProfileColor"] = "Color",
        ["AppTagline"] = "Codex and Claude quotas",
        ["ClaudeAccentColor"] = "Claude color",
        ["ClaudeConnected"] = "Connected",
        ["ClaudeDisconnected"] = "Disconnected",
        ["ClaudeReconnect"] = "Reconnect Claude",
        ["ClaudeConnect"] = "Connect Claude",
        ["ClaudeConnectCode"] = "Connect with code",
        ["ClaudeManualFallback"] = "Automatic connection is unavailable. Complete sign-in in the browser and paste the code below.",
        ["ClaudeDisconnect"] = "Disconnect",
        ["ClaudeConnectSettings"] = "Connect Claude in settings",
        ["ClaudeStale"] = "Out of date",
        ["QuotaDataAsOf"] = "Data from {0}",
        ["ClaudeWaitingBrowser"] = "Complete sign-in in your browser (within 5 minutes).",
        ["ClaudePasteCode"] = "Paste the authorization code (code#state).",
        ["ClaudeSubmitCode"] = "Connect",
        ["ClaudeInvalidCode"] = "Invalid, expired or mismatched code. Start a new connection.",
        ["ClaudeLoginFailed"] = "Could not connect. Try again or connect with code.",
        ["ClaudeLoginCancelled"] = "Connection cancelled or expired.",
        ["ClaudeBrowserDone"] = "Connection authorized. You can close this window.",
        ["ClaudeInvalidCallback"] = "Invalid authorization response. Return to the Tracker.",
        ["ProfileQuotaIndicator"] = "{0}: remaining {1} quota",
        ["AppTitle"] = "Agent Quota Tracker",
        ["Settings"] = "Settings",
        ["CloseSettings"] = "Close settings",
        ["CloseWindow"] = "Close window",
        ["DetailedMode"] = "Detailed mode",
        ["ShowInNotificationArea"] = "Show in notification area",
        ["FadeFloatingWidget"] = "Fade floating widget",
        ["FloatingOpacity"] = "Opacity",
        ["StartMinimizedWithWindows"] = "Start minimized with Windows",
        ["ToggleDetailedMode"] = "Toggle compact/detailed mode",
        ["AlwaysOnTop"] = "Always on top",
        ["Hide"] = "Hide",
        ["Show"] = "Show",
        ["Refresh"] = "Refresh",
        ["Exit"] = "Exit",
        ["DarkTheme"] = "Dark theme",
        ["ToggleTheme"] = "Toggle light or dark theme",
        ["AccentColor"] = "Accent color",
        ["ChooseAccentColor"] = "Choose accent color",
        ["ChooseAccentColorTooltip"] = "Choose the color used for highlights",
        ["Language"] = "Language",
        ["Currency"] = "Currency",
        ["UsdBrlRate"] = "USD to BRL rate (manual)",
        ["CodexPath"] = "Codex path",
        ["Browse"] = "Browse",
        ["AutoDetect"] = "Auto",
        ["Test"] = "Test",
        ["OpenLog"] = "Open log",
        ["Cancel"] = "Cancel",
        ["Apply"] = "Apply",
        ["Agent"] = "Agent",
        ["Subagent"] = "Subagent",
        ["AgentsWorking"] = "{0} agents working",
        ["AgentsWorkingTooltip"] = "Agents working",
        ["ShowWorkingAgents"] = "Show working agents",
        ["OpenAgentChat"] = "Open agent chat",
        ["UnreadAgentCompletions"] = "Unread completed work",
        ["MarkAllCompletedAgentsRead"] = "Mark all completed work as read",
        ["WeeklyQuotaIndicator"] = "Weekly quota remaining indicator",
        ["Working"] = "Working",
        ["Waiting"] = "Waiting",
        ["Completed"] = "Completed",
        ["Failed"] = "Failed",
        ["Cancelled"] = "Cancelled",
        ["Unknown"] = "Unknown",
        ["UnregisteredModel"] = "Model not recorded",
        ["Model"] = "Model",
        ["Effort"] = "Effort",
        ["RunningFor"] = "Running for {0}",
        ["UsageRanking"] = "Usage ranking",
        ["ConsumptionDetails"] = "Consumption details",
        ["Day"] = "day",
        ["Week"] = "week",
        ["Month"] = "month",
        ["Weekly"] = "WEEKLY",
        ["FiveHourWindow"] = "5H WINDOW",
        ["TodayUpper"] = "TODAY",
        ["WeekUpper"] = "WEEK",
        ["MonthUpper"] = "MONTH",
        ["RankingPeriodDay"] = "Ranking period: day",
        ["RankingPeriodWeek"] = "Ranking period: week",
        ["RankingPeriodMonth"] = "Ranking period: month",
        ["DailyUsageCurrentMonth"] = "DAILY USAGE · CURRENT MONTH",
        ["DetailsByChat"] = "Details by chat",
        ["SearchChats"] = "Search chats or projects",
        ["Project"] = "Project",
        ["UnknownProject"] = "No project",
        ["ClearSearch"] = "Clear search",
        ["NoChats"] = "No chats with usage this month.",
        ["PartialTariffEstimate"] = "Partial estimate: some models have no tariff",
        ["Quota"] = "Quota",
        ["WeeklyQuota"] = "Weekly quota",
        ["WeeklyQuotaRemaining"] = "Weekly quota remaining",
        ["WeeklyQuotaInitial"] = "% 7d initial",
        ["WeeklyQuotaRemainingShort"] = "% 7d remaining",
        ["CompactQuota"] = "Compact quota indicator",
        ["QuotaNotReported"] = "Weekly quota not reported",
        ["NoQuotaRecord"] = "no quota record",
        ["LoadingWeeklyQuota"] = "Loading weekly quota",
        ["Loading"] = "Loading",
        ["InsufficientData"] = "Insufficient data for forecast",
        ["ShouldLastUntilReset"] = "Should last until reset",
        ["LimitExhausted"] = "Limit exhausted",
        ["ExhaustionRisk"] = "Risk of exhaustion before reset",
        ["ProjectedForecast"] = "{0} · {1} projected",
        ["ExhaustsAround"] = "runs out around {0}",
        ["Reset"] = "Reset",
        ["LiveData"] = "Live data via Codex",
        ["NoLiveData"] = "No live data",
        ["Costs"] = "Costs",
        ["NoTariff"] = "no tariff",
        ["EstimatedValues"] = "Estimated values",
        ["CachedRead"] = "Cache read",
        ["Input"] = "Input",
        ["Output"] = "Output",
        ["Reasoning"] = "Reasoning",
        ["Total"] = "Total",
        ["Connected"] = "Connected",
        ["ConnectionError"] = "Connection error",
        ["ConnectingToCodex"] = "Connecting to Codex",
        ["StaleReconnecting"] = "Stale: reconnecting",
        ["StaleRetrying"] = "Stale: retrying connection",
        ["TestFailed"] = "Test failed",
        ["CodexNotFound"] = "Error: Codex CLI not found",
        ["ConnectedWeeklyUnavailable"] = "Connected - weekly quota unavailable",
        ["DayNumber"] = "Day {0}",
        ["CodexConversation"] = "Codex conversation",
        ["ConnectedWeeklyRemaining"] = "Connected - weekly quota remaining {0}",
        ["CheckForUpdates"] = "Check for updates",
        ["UpdateCheckChecking"] = "Checking for updates…",
        ["UpdateCheckUpToDate"] = "You're already on the latest version.",
        ["UpdateCheckFailed"] = "Couldn't check for updates.",
        ["UpdateCheckInProgress"] = "A check is already running…",
        ["UpdateAvailableTitle"] = "Update available",
        ["UpdateAvailableMessage"] = "A new version of Agent Quota Tracker is available: {0}",
        ["UpdateNow"] = "Update",
        ["UpdateLater"] = "Later",
        ["UpdateDownloading"] = "Downloading update…",
        ["UpdateDownloadingPercent"] = "Downloading update… {0}%",
        ["UpdateInstalling"] = "Installing and restarting…",
        ["UpdateFailed"] = "Update failed. Please try again later."
    };

    private static readonly IReadOnlyDictionary<string, string> KnownTextKeys = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["Agent"] = "Agent",
        ["Agente"] = "Agent",
        ["Subagent"] = "Subagent",
        ["Subagente"] = "Subagent",
        ["Working"] = "Working",
        ["Em andamento"] = "Working",
        ["Trabalhando"] = "Working",
        ["Waiting"] = "Waiting",
        ["Aguardando"] = "Waiting",
        ["Completed"] = "Completed",
        ["Concluído"] = "Completed",
        ["Failed"] = "Failed",
        ["Falhou"] = "Failed",
        ["Cancelled"] = "Cancelled",
        ["Cancelado"] = "Cancelled",
        ["Unknown"] = "Unknown",
        ["Desconhecido"] = "Unknown",
        ["Risco de esgotar antes do reset"] = "ExhaustionRisk",
        ["Risk of exhaustion before reset"] = "ExhaustionRisk",
        ["Dados insuficientes"] = "InsufficientData",
        ["Insufficient data"] = "InsufficientData",
        ["Deve durar até o reset"] = "ShouldLastUntilReset",
        ["Should last until reset"] = "ShouldLastUntilReset",
        ["Limite esgotado"] = "LimitExhausted",
        ["Limit exhausted"] = "LimitExhausted",
        ["Conversa Codex"] = "CodexConversation",
        ["Codex conversation"] = "CodexConversation",
        ["Sem dados ao vivo"] = "NoLiveData",
        ["No live data"] = "NoLiveData",
        ["Ao vivo via Codex"] = "LiveData",
        ["Dados ao vivo via Codex"] = "LiveData",
        ["Live via Codex"] = "LiveData",
        ["Erro de conexão"] = "ConnectionError",
        ["Connection error"] = "ConnectionError",
        ["Carregando"] = "Loading",
        ["Loading"] = "Loading",
        ["Conectando ao Codex"] = "ConnectingToCodex",
        ["Connecting to Codex"] = "ConnectingToCodex",
        ["Desatualizado: reconectando"] = "StaleReconnecting",
        ["Stale: reconnecting"] = "StaleReconnecting",
        ["Desatualizado: tentando reconectar"] = "StaleRetrying",
        ["Stale: retrying connection"] = "StaleRetrying",
        ["Teste falhou"] = "TestFailed",
        ["Test failed"] = "TestFailed",
        ["Erro: Codex CLI não encontrado"] = "CodexNotFound",
        ["Error: Codex CLI not found"] = "CodexNotFound",
        ["Conectado - quota semanal indisponível"] = "ConnectedWeeklyUnavailable",
        ["Connected - weekly quota unavailable"] = "ConnectedWeeklyUnavailable"
    };

    private static string _languageCode = DefaultLanguageCode;

    public static string CurrentLanguageCode => _languageCode;

    public static string NormalizeLanguage(string? languageCode) =>
        string.Equals(languageCode?.Trim(), EnglishLanguageCode, StringComparison.OrdinalIgnoreCase)
            ? EnglishLanguageCode
            : DefaultLanguageCode;

    public static void Apply(string? languageCode)
    {
        _languageCode = NormalizeLanguage(languageCode);
        var strings = CurrentStrings;
        if (System.Windows.Application.Current is not { } application) return;

        foreach (var item in Portuguese)
            application.Resources[ResourcePrefix + item.Key] = strings.TryGetValue(item.Key, out var text) ? text : item.Value;
    }

    public static string Text(string key)
    {
        if (string.IsNullOrWhiteSpace(key)) return string.Empty;
        return CurrentStrings.TryGetValue(key, out var text)
            ? text
            : Portuguese.TryGetValue(key, out var fallback) ? fallback : key;
    }

    public static bool HasTextKey(string key) => !string.IsNullOrWhiteSpace(key) && Portuguese.ContainsKey(key) && English.ContainsKey(key);

    public static string Format(string key, params object[] arguments) =>
        string.Format(CultureInfo.GetCultureInfo(_languageCode), Text(key), arguments ?? Array.Empty<object>());

    public static string TranslateKnown(string? value)
    {
        var knownValue = value ?? string.Empty;
        if (string.IsNullOrWhiteSpace(knownValue)) return knownValue;
        const string PortugueseRemaining = "Conectado - quota semanal restante ";
        const string EnglishRemaining = "Connected - weekly quota remaining ";
        if (knownValue.StartsWith(PortugueseRemaining, StringComparison.OrdinalIgnoreCase))
            return Format("ConnectedWeeklyRemaining", knownValue.Substring(PortugueseRemaining.Length));
        if (knownValue.StartsWith(EnglishRemaining, StringComparison.OrdinalIgnoreCase))
            return Format("ConnectedWeeklyRemaining", knownValue.Substring(EnglishRemaining.Length));
        return KnownTextKeys.TryGetValue(knownValue, out var key) ? Text(key) : knownValue;
    }

    private static IReadOnlyDictionary<string, string> CurrentStrings =>
        string.Equals(_languageCode, EnglishLanguageCode, StringComparison.Ordinal) ? English : Portuguese;
}
